%% TM - UCL - 18/05/2018

function DisplayInfoPanel(obj, AnimalSessionInfo)


obj.figHandle.animalText = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'fontsize', 12, ...
    'String', ['Mouse: ' AnimalSessionInfo{1}],...
     'HorizontalAlignment','left');
obj.figHandle.seriesText = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Session: ' AnimalSessionInfo{5}],...
     'HorizontalAlignment','left');
obj.figHandle.expText = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Training day nr: ' num2str(AnimalSessionInfo{3})],...
     'HorizontalAlignment','left');
obj.figHandle.Duration = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Duration: ' AnimalSessionInfo{6}],...
     'HorizontalAlignment','left');
obj.figHandle.trials = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Total nr of trials: ' num2str(AnimalSessionInfo{7}) ', of which ' num2str(length(AnimalSessionInfo{10})) ' completed'],...
     'HorizontalAlignment','left');
obj.figHandle.VR = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['VR type: ' AnimalSessionInfo{8}],...
     'HorizontalAlignment','left');
obj.figHandle.trialduration = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Avg. trial duration: ' num2str(AnimalSessionInfo{11}) ' seconds'],...
     'HorizontalAlignment','left');
obj.figHandle.avgspeed = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Avg. moving speed: ' num2str(AnimalSessionInfo{13}) ' cm/s'],...
     'HorizontalAlignment','left');
obj.figHandle.maxspeed = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Max moving speed: ' num2str(AnimalSessionInfo{14}) ' cm/s'],...
     'HorizontalAlignment','left');
obj.figHandle.moving = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Time spent moving (>2cm/s): ' num2str(AnimalSessionInfo{15}) ' %'],...
     'HorizontalAlignment','left');
obj.figHandle.Rewards = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Rewards released: ' num2str(AnimalSessionInfo{16}) ' by user, ' num2str(AnimalSessionInfo{17}) ' passive, ' num2str(AnimalSessionInfo{18}) ' active'],...
     'HorizontalAlignment','left');
obj.figHandle.lickstrial = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Licks per trial: ' num2str(AnimalSessionInfo{19})],...
     'HorizontalAlignment','left');
obj.figHandle.LicksPosition = uicontrol('Style','text',...
    'Parent',obj.figHandle.animalInfoPanel,...
    'String', ['Licks before-after reward relase: ' num2str(AnimalSessionInfo{20}) '-' num2str(AnimalSessionInfo{21})],...
     'HorizontalAlignment','left');
 
% to add spatial frequency info of the textures for DIT task

end
